#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sound-theme-freedesktop
Version  : 0.8
Release  : 3
URL      : http://people.freedesktop.org/~mccann/dist/sound-theme-freedesktop-0.8.tar.bz2
Source0  : http://people.freedesktop.org/~mccann/dist/sound-theme-freedesktop-0.8.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC-BY-3.0 CC-BY-SA-4.0 GPL-2.0
Requires: sound-theme-freedesktop-data = %{version}-%{release}
BuildRequires : gettext
BuildRequires : intltool
BuildRequires : perl(XML::Parser)

%description
FREEDESKTOP SOUND THEME
LICENSES AND ORIGINS:
See CREDITS
RULES:
Similar to those defined by gnome-audio, quoting Elliot Lee:

%package data
Summary: data components for the sound-theme-freedesktop package.
Group: Data

%description data
data components for the sound-theme-freedesktop package.


%prep
%setup -q -n sound-theme-freedesktop-0.8
cd %{_builddir}/sound-theme-freedesktop-0.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604352593
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604352593
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/sounds/freedesktop/index.theme
/usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga
/usr/share/sounds/freedesktop/stereo/audio-channel-front-center.oga
/usr/share/sounds/freedesktop/stereo/audio-channel-front-left.oga
/usr/share/sounds/freedesktop/stereo/audio-channel-front-right.oga
/usr/share/sounds/freedesktop/stereo/audio-channel-rear-center.oga
/usr/share/sounds/freedesktop/stereo/audio-channel-rear-left.oga
/usr/share/sounds/freedesktop/stereo/audio-channel-rear-right.oga
/usr/share/sounds/freedesktop/stereo/audio-channel-side-left.oga
/usr/share/sounds/freedesktop/stereo/audio-channel-side-right.oga
/usr/share/sounds/freedesktop/stereo/audio-test-signal.oga
/usr/share/sounds/freedesktop/stereo/audio-volume-change.oga
/usr/share/sounds/freedesktop/stereo/bell.oga
/usr/share/sounds/freedesktop/stereo/camera-shutter.oga
/usr/share/sounds/freedesktop/stereo/complete.oga
/usr/share/sounds/freedesktop/stereo/device-added.oga
/usr/share/sounds/freedesktop/stereo/device-removed.oga
/usr/share/sounds/freedesktop/stereo/dialog-error.oga
/usr/share/sounds/freedesktop/stereo/dialog-information.oga
/usr/share/sounds/freedesktop/stereo/dialog-warning.oga
/usr/share/sounds/freedesktop/stereo/message-new-instant.oga
/usr/share/sounds/freedesktop/stereo/message.oga
/usr/share/sounds/freedesktop/stereo/network-connectivity-established.oga
/usr/share/sounds/freedesktop/stereo/network-connectivity-lost.oga
/usr/share/sounds/freedesktop/stereo/phone-incoming-call.oga
/usr/share/sounds/freedesktop/stereo/phone-outgoing-busy.oga
/usr/share/sounds/freedesktop/stereo/phone-outgoing-calling.oga
/usr/share/sounds/freedesktop/stereo/power-plug.oga
/usr/share/sounds/freedesktop/stereo/power-unplug.oga
/usr/share/sounds/freedesktop/stereo/screen-capture.oga
/usr/share/sounds/freedesktop/stereo/service-login.oga
/usr/share/sounds/freedesktop/stereo/service-logout.oga
/usr/share/sounds/freedesktop/stereo/suspend-error.oga
/usr/share/sounds/freedesktop/stereo/trash-empty.oga
/usr/share/sounds/freedesktop/stereo/window-attention.oga
/usr/share/sounds/freedesktop/stereo/window-question.oga
